set properties [dict create {*}{
    age         {type enum}
    AHex        {type boolean}
    Alpha       {type boolean}
    bc          {type enum}
    Bidi_C      {type boolean}
    Bidi_M      {type boolean}
    blk         {type enum}
    bmg         {type cp}
    Cased       {type boolean}
    ccc         {type enum}
    CE          {type boolean}
    cf          {type mcp}
    CI          {type boolean}
    Comp_Ex     {type boolean}
    CWCF        {type boolean}
    CWCM        {type boolean}
    CWKCF       {type boolean}
    CWL         {type boolean}
    CWT         {type boolean}
    CWU         {type boolean}
    Dash        {type boolean}
    Dep         {type boolean}
    DI          {type boolean}
    Dia         {type boolean}
    dm          {type mcp}
    dt          {type enum}
    ea          {type enum}
    Ext         {type boolean}
    FC_NFKC     {type deprecated}
    gc          {type enum}
    GCB         {type enum}
    Gr_Base     {type boolean}
    Gr_Ext      {type boolean}
    Gr_Link     {type deprecated}
    Hex         {type boolean}
    hst         {type enum}
    Hyphen      {type deprecated}
    IDC         {type boolean}
    Ideo        {type boolean}
    IDS         {type boolean}
    IDSB        {type boolean}
    IDST        {type boolean}
    InMC        {type enum}
    InSC        {type enum}
    isc         {type deprecated}
    jg          {type enum}
    Join_C      {type boolean}
    JSN         {type name}
    jt          {type enum}
    lb          {type enum}
    lc          {type mcp}
    LOE         {type boolean}
    Lower       {type boolean}
    Math        {type boolean}
    na          {type name}
    na1         {type name}
    Name_Alias  {type name}
    NChar       {type boolean}
    NFC_QC      {type enum}
    NFD_QC      {type boolean}
    NFKC_CF     {type mcp}
    NFKC_QC     {type enum}
    NFKD_QC     {type boolean}
    nt          {type enum}
    nv          {type numeric}
    OAlpha      {type boolean}
    ODI         {type boolean}
    OGr_Ext     {type boolean}
    OIDC        {type boolean}
    OIDS        {type boolean}
    OLower      {type boolean}
    OMath       {type boolean}
    OUpper      {type boolean}
    Pat_Syn     {type boolean}
    Pat_WS      {type boolean}
    QMark       {type boolean}
    Radical     {type boolean}
    SB          {type enum}
    sc          {type enum}
    scf         {type cp}
    scx         {type enumList enumType sc}
    SD          {type boolean}
    slc         {type cp}
    stc         {type cp}
    STerm       {type boolean}
    suc         {type cp}
    tc          {type mcp}
    Term        {type boolean}
    uc          {type mcp}
    UIdeo       {type boolean}
    Upper       {type boolean}
    VS          {type boolean}
    WB          {type enum}
    WSpace      {type boolean}
    XIDC        {type boolean}
    XIDS        {type boolean}
    XO_NFC      {type deprecated}
    XO_NFD      {type deprecated}
    XO_NFKC     {type deprecated}
    XO_NFKD     {type deprecated}
}]
